### ISSUE TITLE
Readline support for `shell` method

### ISSUE THREAD

**Issue by rwp0** [renormalist/Net-SSH-Perl#13]
Apparently unlike with `ssh(1)` utility, the `shell` method of `Net::SSH::Perl` objects does not allow keybindings such as `Ctrl-A` and `Ctrl-E` as most Unix shells and REPL's are expected to provide.

I believe it could be due to lack of Readline library support.

Can we add support with eg. `Term::Readline::GNU`?

**Comment by renormalist** [comment]
Ui ui ui, this repository here isn't in good maintenance mode and I personally don't have time for it, I always only did CPAN releases of bug fixes. You could try your luck at @lkinley 's repository https://github.com/lkinley/Net-SSH-Perl - he did the last real work on this module. But don't let him do the work, he for sure is busy as well, but maybe provide actual code as a well-tested pull request.

Sorry to not give a more promising answer. :-)

**Comment by renormalist** [comment]
Current development happens in https://github.com/briandfoy/net-ssh-perl
I try to migrate this issue into that new repo.
"See you on the other side, Coop."

**Comment by rwp0** [comment]
Good news, thanks!

**Comment by briandfoy** [comment]
Hey @rwp0, we tried to transfer this issue but it might be easier for you to re-add it to https://github.com/briandfoy/net-ssh-perl so you are the author.

If you do that and include `https://github.com/renormalist/Net-SSH-Perl/issues/13` in it, GitHub will show the link between this issue and the new one.

Thanks,

**Comment by renormalist** [comment]
@rwp0 Once you created the ticket in the other repo I will archive this repository here, please ping me once you are done. 

I could not move the ticket by myself for unknown github reasons. 

Thanks.

**Comment by rwp0** [comment]
> @rwp0 Once you created the ticket in the other repo I will archive this repository here, please ping me once you are done.
> 
> I could not move the ticket by myself for unknown github reasons.
> 
> Thanks.

@renormalist 

https://github.com/briandfoy/net-ssh-perl/issues/65

**Comment by renormalist** [comment]
Great, thanks. Closing this ticket here and archiving the repo now.
